/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_webgpuprocessor_free: (a: number, b: number) => void;
export const __wbg_webphotoeditor_free: (a: number, b: number) => void;
export const webgpuprocessor_create: () => any;
export const webphotoeditor_add_mask: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const webphotoeditor_apply: (a: number) => [number, number];
export const webphotoeditor_create_from_rgb_f32: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const webphotoeditor_exif_json: (a: number) => [number, number, number, number];
export const webphotoeditor_get_rgb_f32: (a: number) => any;
export const webphotoeditor_get_rgba_f32: (a: number) => any;
export const webphotoeditor_height: (a: number) => number;
export const webphotoeditor_new: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const webphotoeditor_remove_mask: (a: number, b: number, c: number) => [number, number];
export const webphotoeditor_save_jpeg: (a: number) => any;
export const webphotoeditor_save_png: (a: number) => any;
export const webphotoeditor_save_tiff_linear_srgb_16bit: (a: number) => any;
export const webphotoeditor_save_tiff_linear_srgb_8bit: (a: number) => any;
export const webphotoeditor_save_tiff_srgb_16bit: (a: number) => any;
export const webphotoeditor_save_tiff_srgb_8bit: (a: number) => any;
export const webphotoeditor_set_brightness_tone_curve: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const webphotoeditor_set_lens_distortion_correction: (a: number, b: number) => [number, number];
export const webphotoeditor_set_mask_range: (a: number, b: number, c: number, d: number) => [number, number];
export const webphotoeditor_set_oklch_hue_curve: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const webphotoeditor_set_oklch_lightness_curve: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const webphotoeditor_set_oklch_saturation_curve: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const webphotoeditor_set_tone: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const webphotoeditor_set_vignette: (a: number, b: number) => [number, number];
export const webphotoeditor_set_whitebalance: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const webphotoeditor_width: (a: number) => number;
export const init: () => void;
export const wasm_bindgen_46a9236ac5bcbc21___convert__closures_____invoke___wasm_bindgen_46a9236ac5bcbc21___JsValue__core_f0fd674eaa06beef___result__Result_____wasm_bindgen_46a9236ac5bcbc21___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_46a9236ac5bcbc21___convert__closures_____invoke___js_sys_ed5f3a2b9f4611a2___Function_fn_wasm_bindgen_46a9236ac5bcbc21___JsValue_____wasm_bindgen_46a9236ac5bcbc21___sys__Undefined___js_sys_ed5f3a2b9f4611a2___Function_fn_wasm_bindgen_46a9236ac5bcbc21___JsValue_____wasm_bindgen_46a9236ac5bcbc21___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_46a9236ac5bcbc21___convert__closures_____invoke___wasm_bindgen_46a9236ac5bcbc21___JsValue______true_: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
